### ISSUE TITLE
Compiled DDMIntegratorFunction suffers shape error in `LLVMExec` mode

### ISSUE THREAD

**Issue by SamKG** [PrincetonUniversity/PsyNeuLink#1578]
It seems that DDMIntegratorFunctions suffer from a shape error only when called from `LLVMExec` mode.

_Originally referenced by @jvesely in https://github.com/PrincetonUniversity/PsyNeuLink/pull/1555_

**Comment by jvesely** [comment]
@SamKG, was this hit in `test_scheduler condition`?
a7b795a644e7ec033f5cdb3fae24bfca7e5e14bc enabled `LLVMExec` for those tests without any issue.

**Comment by jvesely** [comment]
DDI works ok several tests. please reopen with an example if the problem persists.
