### ISSUE TITLE
UserWarning: LinearCombination... is generated once during import of psyneulink,...

### ISSUE THREAD

**Issue by jdcpni** [PrincetonUniversity/PsyNeuLink#1669]
ia = ProcessingMechanism(name='INPUT')
ib = ProcessingMechanism(name='OUTPUT')
input_mech = ProcessingMechanism(name='INPUT')
internal_mech = ProcessingMechanism(name='INTERNAL')
output_mech = ProcessingMechanism(name='OUTPUT')
ctl_mech = ControlMechanism(name='CONTROL',
                            control=[(SLOPE, input_mech),
                                     (SLOPE, output_mech)])
icomp = Composition(name="NESTED COMPOSITION",
                    pathways=[([ia, ib],BackPropagation)]
                    )
ocomp = Composition(name='COMPOSITION',
                    pathways=[input_mech, internal_mech, icomp, output_mech],
                    controller=OptimizationControlMechanism(
                        name='CONTROLLER',
                        objective_mechanism=ObjectiveMechanism(monitor=[input_mech,
                                                                        output_mech]),
                        control=(SLOPE, internal_mech))
                    )

ocomp.show_graph()

**Comment by kmantel** [comment]
Fixed by 116fd70
