### ISSUE TITLE
Model documentation: hidden script download links

### ISSUE THREAD

**Issue by kmantel** [PrincetonUniversity/PsyNeuLink#1709]
On the documentation pages for models (example: [Gilzenrat](https://princetonuniversity.github.io/PsyNeuLink/GilzenratModel.html), links to download the python file were visible at one point after `Script: ` at the bottom of each page, but are now invisible. This is due to this css rule that gets placed in `docs/build/html/_static/css/theme.css`:

    article.psyneulink-article .sphx-glr-download-link-note.admonition.note,
    article.psyneulink-article .reference.download.internal, article.psyneulink-article .sphx-glr-signature {
      display: none;
    }

I tried overriding the rule in `docs/source/_static/css/custom.css`, but that failed. I also tried installing previous versions of [psyneulink_sphinx_theme](https://pypi.org/project/psyneulink-sphinx-theme/), in case the recent changes affected it, but that failed also.

**Comment by dillontsmith** [comment]
Thanks for reporting.

I removed the CSS rule that was hiding download links [from the theme directly](https://github.com/dillontsmith/psyneulink_sphinx_theme/commit/1cd4580918f92dbf0e2b4838df95955d603034ae)

I also reenabled `docs/source/_static/css/custom.css` in 6c315a2f00edf324b3c0ef3e8b8d6ca7b1b5986c. CSS rules added to that file will once again be reflected in the compiled docs.
