### ISSUE TITLE
Potential Problem with JSON methods

### ISSUE THREAD

**Issue by kpoling** [PrincetonUniversity/PsyNeuLink#1997]
Hi, this could be a mistake on my end, but I'm pretty sure it is PsyNeuLink error so I thought I should bring it up. When I try and export a relatively small model to a json file using either json_summary method or the write_json_file method I get a recursion error that says "RecursionError: maximum recursion depth exceeded in comparison". 

Here is an example of code that gets the error. I make a composition and then at the bottom either of the two json methods creates the error. 
`
nouns_in = pnl.TransferMechanism(default_variable=np.zeros(8))
rels_in = pnl.TransferMechanism(default_variable=np.zeros(8))
h1 = pnl.TransferMechanism(size=9)
h2 = pnl.TransferMechanism(size=16)
out_sig_I = pnl.TransferMechanism(size = 9)                                 
out_sig_is = pnl.TransferMechanism(size = 12)
out_sig_has = pnl.TransferMechanism(size = 10)
out_sig_can = pnl.TransferMechanism(size = 10)
                                 
p11 = pnl.Pathway(pathway=[nouns_in, h1, h2])
p12 = pnl.Pathway(pathway=[rels_in,h2])
p21 = pnl.Pathway(pathway=[h2,out_sig_I])
p22 = pnl.Pathway(pathway=[h2,out_sig_is])
p23 = pnl.Pathway(pathway=[h2,out_sig_has])
p24 = pnl.Pathway(pathway=[h2, out_sig_can])

rumel_comp = pnl.AutodiffComposition( )

rumel_comp.add_backpropagation_learning_pathway(pathway=p11)
rumel_comp.add_backpropagation_learning_pathway(pathway=p12)
rumel_comp.add_backpropagation_learning_pathway(pathway=p21)
rumel_comp.add_backpropagation_learning_pathway(pathway=p22)
rumel_comp.add_backpropagation_learning_pathway(pathway=p23)
rumel_comp.add_backpropagation_learning_pathway(pathway=p24)

# Recursion error with both of these following lines of code
rumel_comp.json_summary
pnl.write_json_file(rumel_comp, "testing")
                                 
         `

**Comment by kmantel** [comment]
Thanks for the report. I've just merged a fix for the crash. If you need the changes before it reaches release, install the devel branch:  `pip install git+https://github.com/PrincetonUniversity/PsyNeuLink.git@devel`. But unfortunately, I don't think python->json->python for learning will work in general as of now, and it will take some time to implement.
