### ISSUE TITLE
updates from dependabot fail to update the documentation

### ISSUE THREAD

**Issue by jvesely** [PrincetonUniversity/PsyNeuLink#2144]
dependabot can automatically merge dependency bumps to devel.
However, when the resulting commit on devel triggers documentation build, it fails to upload the updated documentation (see [0,1]).
manually restarting the CI jobs works OK and updates the documentation. [2]

[0] https://github.com/PrincetonUniversity/PsyNeuLink/runs/3844044313?check_suite_focus=true
[1] https://github.com/PrincetonUniversity/PsyNeuLink/runs/3843575556?check_suite_focus=true
[2] https://github.com/PrincetonUniversity/PsyNeuLink/runs/3844400391?check_suite_focus=true

**Comment by kmantel** [comment]
Seems like it could be related to some of the changes listed [here](https://github.blog/changelog/2021-10-06-github-actions-workflows-triggered-by-dependabot-prs-will-respect-permissions-key-in-workflows/)? Also related https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544

**Comment by jvesely** [comment]
Thanks that would explain why my attempts to fix it using permissions didn't work.
I'm not sure how much the above security constraints help with the push event, other than shift blame (dependabot -> 'the person who clicked merge'.
Does dependabot check who asked for automerge?
At any rate, after merging to devel the damage is already done so we can just bump the push action permissions.
