### ISSUE TITLE
Documentation Search Box

### ISSUE THREAD

**Issue by tylergiallanza** [PrincetonUniversity/PsyNeuLink#2193]
The "Search Docs" box on the psyneulink website, e.g. [https://princetonuniversity.github.io/PsyNeuLink/search.html](https://princetonuniversity.github.io/PsyNeuLink/search.html), is not working. The output says "Searching..." rather than returning the results of the search.

**Comment by kmantel** [comment]
This started with sphinx 3.4.0 and seems to be the same as https://github.com/sphinx-doc/sphinx/issues/8623. I see now `psyneulink_sphinx_theme` is based on `sphinx_rtd_theme`, so the solution is the same, and this should be resolved after `psyneulink_sphinx_theme` is updated.

**Comment by kmantel** [comment]
This was fixed in #2201 (not sure why the auto close didn't work)
