### ISSUE TITLE
Potential for false-passing tests due to np.allclose use

### ISSUE THREAD

**Issue by kmantel** [PrincetonUniversity/PsyNeuLink#2609]
For `test_parameter_CIM_routing_from_ControlMechanism`:

https://github.com/PrincetonUniversity/PsyNeuLink/blob/06f3006ab7a0a5e72423267c47db767c004eda3f/tests/composition/test_interfaces.py#L544-L559

The value of `res` above is the output of the last trial run by `ocomp` (`[array([4.])]`). It appears that the test's intent is to verify with tolerance the output of all trials of `ocomp`. This test happens to pass because the input for each trial is the same, and `np.allclose` still returns True as long as each individual numeric value is close, even if the shape is different. So, if this test intended to check all trials and we were to change the inputs, it may incorrectly pass, for example:

```python
res = ocomp.run([[0], [0], [2]]) 
assert np.allclose(res, [[4], [4], [4]])
```
would pass, although `ocomp.results` is `[[array([0.])], [array([0.])], [array([4.])]]`.

`np.allclose` is used extensively in our tests, so regardless of this specific example, it seems possible there are some other tests that are affected. In general, if the intent with a test like this is just to verify the final trial, only a single value should be used to compare for clarity. If the result for all trials is meant to be verified, something like `numpy.testing.assert_array_almost_equal` should be used to ensure the proper assert is happening.

**Comment by jvesely** [comment]
@kmantel should this one be closed?

**Comment by kmantel** [comment]
Yeah, not sure why the github keyword missed it.
