### ISSUE TITLE
log nparray() drops entries with duplicate time points.

### ISSUE THREAD

**Issue by davidt0x** [PrincetonUniversity/PsyNeuLink#2842]
Calls to `nparray()` on log don't report entries with duplicate time values. This is inconsistent with the report generated by `print_entries()`. 

Reproducible example from @jongkeesbj 

```
import psyneulink as pnl

my_lca = pnl.LCAMechanism(
        size=2,
        function=pnl.Logistic(gain=1.0),
        termination_measure=pnl.TimeScale.TRIAL,
        termination_threshold=10,
    )

my_lca.set_log_conditions([pnl.RESULT])

comp = pnl.Composition(my_lca)

comp.run([1, 0])

my_lca.log.print_entries() # This shows results for all 10 time steps
my_lca.log.nparray() # This shows results only for the last time step?
``` 

This issue seems to be caused by nparray() using `Log._assemble_entry_data` which drops duplicate entries with the same time. I think the correct fix would be to add a further level of granularity to time that includes the execution number.

**Comment by kmantel** [comment]
Fixed by #2844
